version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'python run.py --port=5000'
        ports:
            - 5000:5000
        volumes:
            - .:/app