version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        image: microblock-backend
        ports:
            - 5000:5000
    client:
        build:
            context: .
            dockerfile: Dockerfile.client
        image: microblock-client
        ports:
            - 3000:3000
