version: '3.8'
services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile.backend
        ports:
            - 5000:5000
    client:
        build:
            context: .
            dockerfile: Dockerfile.client
        ports:
            - 3000:80
